spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:pidevdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.port=8082
server.servlet.context-path=/PIDEV

api.url=${ML_API_URL:http://127.0.0.1:8000/apply_dbscan}
prediction.api.url=${PREDICTION_API_URL:http://127.0.0.1:8000/Prediction}

#email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME:}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true